INSERT INTO UTILISATEUR (ID_UTILISATEUR, UTI_LOGIN, UTI_PASSWORD, UTI_ENABLED) VALUES (1, 'admin', 'admin', true);
INSERT INTO UTILISATEUR (ID_UTILISATEUR, UTI_LOGIN, UTI_PASSWORD, UTI_ENABLED) VALUES (2, 'user', 'user', true);

INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (1, 'APPLI_TUTO_ADMIN');
INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (2, 'APPLI_TUTO_USER');
INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (3, 'APPLI_TUTO_USER');
INSERT INTO ROLE (ID_ROLE, ROL_NOM) VALUES (4, 'APPLI_TUTO_USER');

INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (1, 1);
INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (1, 2);
INSERT INTO ROLE_UTILISATEUR (ID_UTILISATEUR, ID_ROLE) VALUES (2, 3);

COMMIT;